# Generated by Django 2.2.2 on 2019-06-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssh', '0002_querymanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='querymanager',
            name='parameters',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
